config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    registrations: "users/registrations"
  }

  devise_for :admins, controllers: { 
    sessions: "admins/sessions", 
    registrations: "admins/registrations"
  }
  
  resources :admins do
    
    collection do
      resources :products do 
        
        collection do 
          get :batch_products
        end

        collection do
          post :add_batch
        end

        collection do
          post :validate_batch
        end
        
      end        
    end

    collection do
      resources :categories
    end   
  end

  root to: "products#index"
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories, join_table: :product_categories
  has_and_belongs_to_many :orders, join_table: :order_products
  belongs_to :admins

  validates :name, :description, :categories, :status, :price, presence: true
  validates :recurring_type, :recurring_no_of_payments, presence: true, if: :is_recurring_billing?
  validates :recurring_custom_type, :recurring_custom_bill_on, presence: true, if: :is_recurring_custom_billing?
  validates :trial_price, :trial_days, presence: true, if: :free_trial_allowed?

  STATUS_VALUES = { active: 1, inactive: 2, archived: 3 }
  RECUURING_BILLING_TYPE = { :Weekly => 1,  :Monthly => 2, :Quaterly => 3, :Custom => 4}
  RECUURING_CUSTOME_TYPE = {:Days => 1, :Weeks => 2, :Months => 3}

  default_scope { order('created_at DESC') }




  def self.search(search)
    if search
      self.where("name like ?", "%#{search}%")
    else
      self.all
    end
  end

  def is_recurring_billing?
    is_recurring?
  end

  def is_recurring_custom_billing?
    recurring_type == RECUURING_BILLING_TYPE[:Custom]
  end

  def free_trial_allowed?
    has_trial?
  end

end

app/controllers/products_controller.rb
class ProductsController < AdminsController
  
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distict: true).paginate(page: params[:page], per_page: 10)
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def batch_products
    @product = Product.new
    @categories = Category.all
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all 
  end

  def create 
    if params[:product].present?
      @product = Product.new(product_params)
      if @product.save
        redirect_to products_path
      else
        render 'new'
      end
    elsif params[:products].present?
      params[:products].each do |product| 
        @batch_products = Product.new(batch_product_params(product.last['product']))
        @batch_products.save
      end
      respond_to do |format|   
        format.json { render json: {:success => true} }  
      end
    end      
  end

  def add_batch
    @no_of_forms = batch_param.present? ? batch_param.to_i : 1
    @categories = Category.all
    respond_to do |format|
      format.js
    end
  end


  def validate_batch
    product_response = [] 
    params[:products].each do |product|
      @batch = Product.new(batch_product_params(product.last['product']))
      @batch.valid? ? product_response.push(message: true) :  product_response.push(message: false, counter: product.first, product_errors:  @batch.errors.full_messages)
    end
    respond_to do |format|   
      error  = product_response.detect{|pr| pr[:message] == false}
      if error.present?  
        format.json { render json: {success: false, errors: list_of_errors(product_response)}}
      else
        format.json { render json: {:success => true} }
      end   
    end
  end


  def update
    @product = Product.find(params[:id])
   
    if @product.update(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :category_ids, :status, :price, 
      :is_recurring, :recurring_type, :recurring_no_of_payments, :recurring_custom_bill_on, 
      :recurring_custom_type, :has_trial, :trial_price, :trial_days, :product_ids => [])
  end

  def batch_param
    params[:add_batch_products][:no_of_forms] 
  end

  def batch_product_params(params)
    ac_params = ActionController::Parameters.new(params)
    ac_params.permit(:name, :description, :price, :category_ids, :status, :is_recurring, :recurring_type, :recurring_custom_bill_on, :recurring_custom_type, :recurring_no_of_payments, :has_trial, :trial_price, :trial_days)
  end

  def list_of_errors(errors_list)
    errors = []
    messages = errors_list.each do |e|
      e[:counter].present? ? errors.push(e[:counter]) : ""
      e[:product_errors].present? ? errors.push(e[:product_errors]) : ""
    end
    errors  
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_new_product.html.erb
<div class = "new-product-form">
<%= form_for :product, :html => {id: "batch-form-new", :class => "form-batch"}, url:  products_path do |f| %>
<div class = "left-container">
   <div class = "product_new_name">
    <%= f.text_field :name , placeholder: "name"%>
   </div></br>
    <div class="clearfix"></div>

   <div class = "product_new_description">
    <%= f.text_area :description , placeholder: "short description"%>
   </div></br>

   <div class = "product_new_price">
    <%= f.text_field :price , placeholder: "price"%>
   </div></br>
</div>


<div class = "center-container">

   <div class = "product_category">      
      <%= f.select :category_ids, @categories.present? ? @categories.collect{|c| [c.name, c.id]} : "" , {prompt: "Category"}, id: "list_of_categories" %>
      <%= button_tag("+Add new ",type: 'button', onClick: "addNewCategory(this)", id:"new-category")%> 
   </div></br>
      
    <div class = "save-category">
      <%= text_field_tag 'categories', nil, placeholder: 'Add new Category', id: "new-category-field" %>
      <%= button_tag("Save Category ",type: 'button', onClick: "saveCategory()")%>
    </div>   

   <div class = "product_status">
      <%= f.select :status, Product::STATUS_VALUES, {prompt: "Select status"}%>
   </div></br>

</div>

<div class="right-contianer check-margin">
   
   <div class="product-check-box">
      <%= f.check_box :is_recurring, class: 'product_is_recurring' %>
      <%= f.label "Recurring billing" %> 
   </div></br>

   <div class="recurring">
  
      <%= f.select :recurring_type, Product::RECUURING_BILLING_TYPE, {prompt: "Select billing type"}, class: "product_recurring_type select-billing"%>

    <div class="recurring_custom_bill_on">
      <%= f.label "Bill every:" %>
      <%= f.text_field :recurring_custom_bill_on , value: 1%>
    </div></br>

    <div class="recurring_custom_type">
      <%= f.select :recurring_custom_type, Product::RECUURING_CUSTOME_TYPE, {prompt: "Select custom billing type"} %>
    </div></br>

    <div class="product_recurring_no_of_payments">
      <%= f.text_field :recurring_no_of_payments , placeholder: "No of Payments"%>
    </div></br>

   </div>


   <div class = "product_has_trial  product-check-box">
      <%= f.check_box :has_trial, class: "product_trial trial-check-box" %>
      <%= f.label "Allow free trial" %> 
   </div></br>

   <div class = "product_trial_price prt_trial">
      <%= f.text_field :trial_price , placeholder: "Trial Price"%>
   </div></br>

   <div class = "product_trial_days prt_trial">
      <%= f.text_field :trial_days , placeholder: "Trial Days"%>
   </div></br>

  <p>
    <%= f.submit "Save Product", class: "save-product-btn"%>
  </p>
 
<% end %>

</div>
</div>

app/views/products/_bulk_products.html.erb
<div class = "left-container">
   <div class = "product_name">
    <%= f.text_field :name , placeholder: "name"%>
   </div></br>

   <div class = "product_description">
    <%= f.text_area :description , placeholder: "short description"%>
   </div></br>

   <div class = "product_price">
    <%= f.text_field :price , placeholder: "price"%>
   </div></br>
</div>


<div class = "center-container">

   <div class = "product_category">
      <%= f.select :category_ids, @categories.present? ? @categories.collect{|c| [c.name, c.id]} : "" , {prompt: "Category"}, id: "list_of_categories" %>
      <button type="button" class = "add_new_category">+Add new</button>   
   </div></br>

   <div class = "product_status">
      <%= f.select :status, Product::STATUS_VALUES, {prompt: "Select status"}%>
   </div></br>

</div>

<div class = "right-contianer">
   
   <div class = "product_is_recurring">
      <%= f.check_box :is_recurring, id: "product_recurring" %>
      <%= f.label "Recurring billing" %> 
   </div></br>

   <div class = "recurring">
  
      <div class = "product_recurring_type">
         <%= f.select :recurring_type, Product::RECUURING_BILLING_TYPE, {prompt: "Select billing type"}, id: "product_recurring_type"%>
      </div></br>

      <div class = "recurring_custom_bill_on">
         <%= f.label "Bill every:" %>
         <%= f.text_field :recurring_custom_bill_on , value: 1%>
      </div></br>

      <div class = "recurring_custom_type">
         <%= f.select :recurring_custom_type, Product::RECUURING_CUSTOME_TYPE, {prompt: "Select custom billing type"} %>
      </div></br>

      <div class = "product_recurring_no_of_payments">
         <%= f.text_field :recurring_no_of_payments , placeholder: "No of Payments"%>
      </div></br>

   </div>


   <div class = "product_has_trial">
      <%= f.check_box :has_trial, id: "product_trial" %>
      <%= f.label "Allow free trial" %> 
   </div></br>

   <div class = "product_trial_price">
      <%= f.text_field :trial_price , placeholder: "Trial Price"%>
   </div></br>

   <div class = "product_trial_days">
      <%= f.text_field :trial_days , placeholder: "Trial Days"%>
   </div></br>

</div>
<%= form_for :category, url: categories_path, :remote => true  do |c| %>
  
  <div class = "save-category">
    <%= c.text_field :name , placeholder: "Category name" %>
    <%= c.submit 'Save Category'%>
  </div>
<% end %>

app/views/products/_form.html.erb
<div class="batch-append">

<%= form_for :product, :html => {id: "batch-form", :class => "form-batch"}, url:  products_path do |f| %>
<div class = "left-container">
   <div class = "product_name">
    <%= f.text_field :name , placeholder: "name"%>
   </div></br>

   <div class = "product_description">
    <%= f.text_area :description , placeholder: "short description"%>
   </div></br>

   <div class = "product_price">
    <%= f.text_field :price , placeholder: "price"%>
   </div></br>
</div>


<div class = "center-container">

   <div class = "product_category">      
      <%= f.select :category_ids, @categories.present? ? @categories.collect{|c| [c.name, c.id]} : "" , {prompt: "Category"}, id: "list_of_categories" %>
      <%= button_tag("+Add new ",type: 'button', onClick: "addNewCategory(this)", id:"new-category")%> 
   </div></br>
      
    <div class = "save-category">
      <%= text_field_tag 'categories', nil, placeholder: 'Add new Category', id: "new-category-field" %>
      <%= button_tag("Save Category ",type: 'button', onClick: "saveCategory()")%>
    </div></br>   

   <div class = "product_status">
      <%= f.select :status, Product::STATUS_VALUES, {prompt: "Select status"}%>
   </div></br>

</div>

<div class="right-contianer">
   
   <div>
      <%= f.check_box :is_recurring, class: 'product_is_recurring' %>
      <%= f.label "Recurring billing" %> 
   </div></br>

   <div class="recurring custom-select">
  
      <%= f.select :recurring_type, Product::RECUURING_BILLING_TYPE, {prompt: "Select billing type"}, class: "product_recurring_type"%>

    <div class="recurring_custom_bill_on">
      <%= f.label "Bill every:" %>
      <%= f.text_field :recurring_custom_bill_on , value: 1%>
    </div></br>

    <div class="recurring_custom_type">
      <%= f.select :recurring_custom_type, Product::RECUURING_CUSTOME_TYPE, {prompt: "Select custom billing type"} %>
    </div></br>

    <div class="product_recurring_no_of_payments">
      <%= f.text_field :recurring_no_of_payments , placeholder: "No of Payments"%>
    </div></br>

   </div>


   <div class = "product_has_trial">
      <%= f.check_box :has_trial, class: "product_trial" %>
      <%= f.label "Allow free trial" %> 
   </div></br>

   <div class = "product_trial_price custom-trial trial-pr">
      <%= f.text_field :trial_price , placeholder: "Trial Price"%>
   </div></br>

   <div class = "product_trial_days custom-trial">
      <%= f.text_field :trial_days , placeholder: "Trial Days"%>
   </div></br>

     <p>
  </p>
 
<% end %>

</div>
</div>

app/views/products/add_batch.js.erb
<%(1..@no_of_forms).each do |i| %>
  $('#batch_product').append('<%=j render partial: 'form'%>')
  var new_id = 'batch-form'+<%=i%>;
  $('#batch-form').attr('id', new_id);
  $('#new-category').attr('id', 'new-category'+<%=i%>);
<% end %>

$(".product_is_recurring").each(function (){
  var recurring = $(this);

  if(this.checked){
    recurring.parent().parent().find('.recurring').show('slow');
  }
  else{
    recurring.parent().parent().find('.recurring').hide();
    recurring.parent().parent().find('.recurring_custom_bill_on').hide();
    recurring.parent().parent().find('.recurring_custom_type').hide();
  }
});

$(".product_trial").each(function (index){
  var trial = $(this);

  if(this.checked){
    trial.parent().parent().find('.product_trial_price').show('slow');
    trial.parent().parent().find('.product_trial_days').show();
  }
  else{
    trial.parent().parent().find('.product_trial_price').hide('slow');
    trial.parent().parent().find('.product_trial_days').hide();
  }
});

app/views/products/batch_products.html.erb
<div class="add-products">
  <h2>Add Multiple Products</h2>
  <div class="add-products-form">
    <div id = "batch_product" class = "bulk-products">
      <%= render  partial: "form"%>
    </div> 
  </div>
  <div class="batch-wrapper">
    <div class = "all-products">
      <%= button_tag "Save all products", id: "save-all-products", onclick: "submitBatch();" %> 
    </div>
    <div class = "add-more-products">
      <%= form_for :add_batch_products, url: add_batch_products_path, :remote => true  do |c| %>
        <%= c.submit 'Add more products', class: "batch-btn"%>
        <%= c.text_field :no_of_forms , value: 1, class: "no_of_forms"%>
      <% end %>
    </div>
  </div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/destroy.js.erb
$("#product<%=@product.id%>").hide("slow");

app/views/products/edit.html.erb
<div class = "single-product">
  <h2>Edit Product</h2>
  <%= form_for :product, :html => {id: "batch-form", :class => "form-batch"}, url:  product_path, method: :patch  do |f| %>
  <div class = "left-container">
     <div class = "product_name">
      <%= f.text_field :name , placeholder: "name"%>
     </div></br>

     <div class = "product_description">
      <%= f.text_area :description , placeholder: "short description"%>
     </div></br>

     <div class = "product_price">
      <%= f.text_field :price , placeholder: "price"%>
     </div></br>
  </div>


  <div class = "center-container">

     <div class = "product_category">      
        <%= f.select :category_ids, @categories.present? ? @categories.collect{|c| [c.name, c.id]} : "" , {prompt: "Category"}, id: "list_of_categories" %>
        <%= button_tag("+Add new ",type: 'button', onClick: "addNewCategory(this)", id:"new-category")%> 
     </div></br>
        
      <div class = "save-category">
        <%= text_field_tag 'categories', nil, placeholder: 'Add new Category', id: "new-category-field" %>
        <%= button_tag("Save Category ",type: 'button', onClick: "saveCategory()")%>
      </div></br>   

     <div class = "product_status">
        <%= f.select :status, Product::STATUS_VALUES, {prompt: "Select status"}%>
     </div></br>

  </div>

  <div class="right-contianer">
     
     <div>
        <%= f.check_box :is_recurring, class: 'product_is_recurring' %>
        <%= f.label "Recurring billing" %> 
     </div></br>

     <div class="recurring">
    
        <%= f.select :recurring_type, Product::RECUURING_BILLING_TYPE, {prompt: "Select billing type"}, class: "product_recurring_type"%>

      <div class="recurring_custom_bill_on">
        <%= f.label "Bill every:" %>
        <%= f.text_field :recurring_custom_bill_on , value: 1%>
      </div></br>

      <div class="recurring_custom_type">
        <%= f.select :recurring_custom_type, Product::RECUURING_CUSTOME_TYPE, {prompt: "Select custom billing type"} %>
      </div></br>

      <div class="product_recurring_no_of_payments">
        <%= f.text_field :recurring_no_of_payments , placeholder: "No of Payments"%>
      </div></br>

     </div>


     <div class = "product_has_trial">
        <%= f.check_box :has_trial, class: "product_trial" %>
        <%= f.label "Allow free trial" %> 
     </div></br>

     <div class = "product_trial_price">
        <%= f.text_field :trial_price , placeholder: "Trial Price"%>
     </div></br>

     <div class = "product_trial_days">
        <%= f.text_field :trial_days , placeholder: "Trial Days"%>
     </div></br>

    <p>
      <%= f.submit "Save Product"%>
    </p>
   
  <% end %>

  </div>
</div>

app/views/products/index.html.erb
<div class="listing-table">
<%= link_to 'Add new product', new_product_path%>

<h2>List of Products</h2>


<%= search_form_for @q do |f| %>
  <div class="field">
  </div>
<table class="table table-striped table-bordered">
  <tr>
    <th><%= sort_link(@q, :name, 'Name') %></th>
    <th><%= sort_link(@q, :price, 'Price') %></th>
    <th><%= sort_link(@q, :status, 'Status') %></th>

    <th>Status</th>
    <th>Recurring</th>
    <th>Trial</th>
    <th colspan="2">Edit</th>
  </tr>
  <tr>
    <td><%= f.text_field :name_cont%></td>
    <td><%= f.text_field :price_cont%></td>
    <td><%= f.text_field :status_cont%></td>
    <td><%= f.text_field :is_recurring_cont%></td>
    <td><%= f.text_field :has_trial_cont%></td>
  </tr>

  <div class="actions">
    <%= f.submit "search"%>
  </div>
<% end %>
 
  <% @products.each do |product| %>
    <% status = Product::STATUS_VALUES.key(product.status)%>
    <% recurring = product.is_recurring? ? "yes" : "no" %>
    <% trial = product.has_trial? ? "yes" : "no" %>  
    <tr id = "product<%=product.id%>">
      <td><%= product.name %></td>
      <td><%= number_to_currency(product.price) %></td>
      <td><%= status %></td>
      <td><%= recurring %></td>
      <td><%= trial%></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Delete', product_path(product),
              method: :delete,:remote => true,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <div class="page_info">
    <%= page_entries_info @products %>
  </div>
</table>
  <div class="digg_pagination"> 
    <%= will_paginate @products, :container => false %>
  </div>
</div>

app/views/products/new.html.erb
<div class = "new_single_product">
  <div class="heading">
    <span>Add New Product</span>
    <%= link_to 'Add batch products', batch_products_products_path %>
  </div>
  <div class = "single-product">
    <%= render  partial: "add_new_product"%>
  </div>
</div>